### ISSUE TITLE
Release tweaks

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/tactool#1]
## Summary

As a TACTool developer, I want to tweak the GitHub version so that the application is suitable for public release.

## Description

There are a few tasks to tidy up the repository now that it is on GitHub.

## Acceptance criteria

+ [x] LICENCE file is added with GPLv3 licence
+ [x] Licence and copyright statement added (see [ETLHelper version](https://github.com/BritishGeologicalSurvey/etlhelper#licence) for example)
+ [x] Version history back to current `main` is purged to reduce repository size (will need force push)
+ [x] CI pipeline configured in GitHub actions to test and build application

**Comment by leorudczenko** [comment]
All objectives in the acceptance criteria have now been completed.
