### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by tomarney** [BritishGeologicalSurvey/tactool#13]
My lab work would have taken significantly longer without TACtool, and I'm very grateful for all the work put in by the people behind it!

I would like to cite or acknowledge the app in my papers (in prep.) - how would you like me to do so?

**Comment by tomarney** [comment]
The [Journal of Open Source Software](https://joss.theoj.org/) might be a good way to publish, if that's what you want to do

**Comment by volcan01010** [comment]
Hi Tom,

I'm delighted that you have found the tool helpful.  Thanks also for getting in touch, as it is really satisfying to hear that our work is being put to good use.

That's a good question about how to cite; we haven't really thought about that so far.

We have done various things in the past e.g.

+ A full JOSS article.  We did this with [PyVOLCANS](https://joss.theoj.org/papers/10.21105/joss.03649); was more work than expected and took over 6 months.  For TACtool, I think that we'd have to give it a bit more time to gather a demonstrable user-base before we could submit there. 
+ Cite a related scientific paper.  We did this with [disolve](https://github.com/BritishGeologicalSurvey/disolv).  I don't think that this applies here, however, as there isn't any science in the software.
+ Generate a DOI with Zenodo.  We did this with [Ash Model Plotting](https://github.com/BritishGeologicalSurvey/ash-model-plotting).  This gives a permanent identifier to the code, which we can populate with full metadata. The DOIs aren't tracked in citation indexes (yet), however.
+ Cite the GitHub URL.  This is the easiest way, but has the disadvantages that the citation would not contain full author information and that URLs are sometimes discouraged in citations.

I think that we should go with the Zenodo option.  I like the way that GRASS GIS software handles this, and I think that this is appropriate as it is a utility software created by a team of developers.  The [GRASS GIS Citation page](https://grass.osgeo.org/about/citation/) gives examples of the format.  Following the link to Zenodo includes full author information, including their ORCID IDs, which link to their academic profiles.  We could do the same, but with "British Geological Survey" as the development team name.

So:

+ @dvalters - can you please set up a Zenodo link for us like we did with Ash Model Plotting?
+ We'll talk to Matt et. al. and find out the all the author metadata that we need for the record.
+ We'll talk to @pdbebgs to see if there is anything else to consider e.g. does UKRI count as the organisation? Should the team be BGS Informatics?

@tomarney: please cite with the GitHub URL in your draft paper as a temporary measure:

```
British Geological Survey (2023) TACtool Software, Version 1.3.0. British Geological Survey. https://github.com/BritishGeologicalSurvey/tactool
```

We will keep this issue open and update it as things change.  As a minimum, I'd expect that we could replace the GitHub URL with a DOI.

Cheers,
John

**Comment by dvalters** [comment]
Hi all, Could you please send me your OrciD IDs if you have one, and your name and institution as well. (You can reply to decval@bgs.ac.uk if preferred)

(Does anyone know Dan and Connor's contact details now?)

- Connor Newstead
- Dan Sutton
- Declan Valters
- Leo Rudczenko
- John A Stevenson

**Comment by volcan01010** [comment]
My ORCID ID: https://orcid.org/0000-0002-2245-1334

@kerberpolis - Would you like to be included in the Zenodo record for TACTool?  Please send Declan your details.

**Comment by dvalters** [comment]
[like]  Declan Valters - BGS reacted to your message:
________________________________

**Comment by dvalters** [comment]
It is now published on Zenodo with the DOI: [10.5281/zenodo.11236873](https://zenodo.org/doi/10.5281/zenodo.11236873) 🥳 

Various citation/reference formats are given at the Zenodo link above

(If there are any omissions/errors in the metadata, these can still be edited)

**Comment by dvalters** [comment]
Here is an APA citation for example: 

> Rudczenko, L., Newstead, C., Stevenson, J. A., Sutton, D., Valters, D. A., & Horstwood, M. (2024). TACtool - A graphical tool for selecting points for analysis on an SEM image (1.3.0). GitHub. https://doi.org/10.5281/zenodo.11236874

**Comment by leorudczenko** [comment]
Hi @tomarney, we are going to be submitting a paper to the Journal of Open Source Software (JOSS) in the near future. To do this, we need some evidence of usage/citations. Is there any link you could provide to your paper so that we can show this? Even if it is still in the submission stage, a link to an open review or a preprint of the paper would be great!

**Comment by tomarney** [comment]
Hi @leorudczenko my paper is still in prep and probably won't be released as a preprint. I'll let you know when it's published, but that won't be for quite a while I would think. Sorry!

**Comment by tomarney** [comment]
I've just submitted a paper with a reference to the zenodo DOI 🙂
If your JOSS paper is anywhere near publication, I could change the reference in review. I realise it might be a bit of a chicken-and-egg thing for us both wanting to cite the peer-reviewed versions!

**Comment by leorudczenko** [comment]
Hi again Tom, thank you very much for the update, that is great to hear! Unfortunately our paper has been delayed and is still in the writing stage. But if your paper is published before ours is submitted then it would be great for us to cite yours 🙂
