### ISSUE TITLE
Add hint circle to spot-laying cursor

### ISSUE THREAD

**Issue by tomarney** [BritishGeologicalSurvey/tactool#6]
I have yet to try and transfer spots to the laser, but this is already so useful, thank you!

To make it easier to lay the spots in the right place first time, it would be great if you could show a 'ghost' circle of the right size when mousing over the image, as long as it doesn't obscure the image below it too much (maybe a 1px outline?).

**Comment by leorudczenko** [comment]
Hey Tom, it's great to hear that you're finding TACtool so useful! :)

That is a very good suggestion for a new feature. We're currently working on a re-coordination feature for SEM exports, but we'll certainly keep this idea in mind for future updates. Thanks a lot! :)
