### ISSUE TITLE
main.py won't run after clone (module not found error)

### ISSUE THREAD

**Issue by tomarney** [BritishGeologicalSurvey/tactool#8]
I tried to clone and run TACtool on my Win10 machine with miniconda, but I got the following error from the Anaconda Powershell Prompt:

```pwsh
(tactool-windows) PS C:\repos\BritishGeologicalSurvey\tactool> c:\Users\<myusername>\miniconda3\envs\tactool-windows\python.exe tactool/main.py --dev
Traceback (most recent call last):
  File "C:\repos\BritishGeologicalSurvey\tactool\tactool\main.py", line 11, in <module>
    from tactool.window import Window
ModuleNotFoundError: No module named 'tactool'
(tactool-windows) PS C:\repos\BritishGeologicalSurvey\tactool>
```

in VSCode I did a global search for `from tactool.` and replaced with `from ` (i.e. deleted tactool namespace) and it runs fine.

Have I done something wrong? if so, perhaps the installation instructions in the README need updating.

Thanks!

**Comment by leorudczenko** [comment]
Hi Tom! This sounds like an issue with your Python path variable. Did you follow the instructions in the `README` [here](https://github.com/BritishGeologicalSurvey/tactool#running-the-program)?

**Comment by tomarney** [comment]
Ok, sounds like that's what's going wrong for me. Thanks!
